---

#-------------------------------------------------------------------------------
# BASH
#-------------------------------------------------------------------------------

bash_tmout: 'disable'

#-------------------------------------------------------------------------------
# GROUP
#-------------------------------------------------------------------------------

group_config_all:
  - {name: 'example', state: 'true', gid: '1000'}

#-------------------------------------------------------------------------------
# NANO
#-------------------------------------------------------------------------------

nano_state: 'remove'

#-------------------------------------------------------------------------------
# NTPD
#-------------------------------------------------------------------------------

ntpd_state: 'cronjob'

ntpd_server:
  - {address: 'ntp01.example.com', options: {'burst', 'prefer', 'minpoll 4', 'maxpoll 6'}, comment: 'h_ntp01'}
  - {address: 'ntp02.example.com', options: {'burst', 'prefer', 'minpoll 4', 'maxpoll 6'}, comment: 'h_ntp02'}
  - {address: 'ntp03.example.com', options: {'burst', 'prefer', 'minpoll 4', 'maxpoll 6'}, comment: 'h_ntp03'}
  - {address: 'ntp04.example.com', options: {'burst', 'prefer', 'minpoll 4', 'maxpoll 6'}, comment: 'h_ntp04'}

ntpd_monitor_mail_from_address: "root@example.com"

ntpd_monitor_mail_to_address: ["admin@example.com"]

ntpd_monitor_mail_state: 'true'

#-------------------------------------------------------------------------------
# OPENSSH
#-------------------------------------------------------------------------------

openssh_allow_users: ['example']

openssh_password_authentication: 'no'

#-------------------------------------------------------------------------------
# PERIODIC
#-------------------------------------------------------------------------------

periodic_daily_output: '/dev/null'

periodic_monthly_output: '/dev/null'

periodic_weekly_output: '/dev/null'

#-------------------------------------------------------------------------------
# FREEBSD_PF
#-------------------------------------------------------------------------------

freebsd_pf_macros_all:
  - {name: 'n_base', value: '10.1.1.0/24', comment: 'n_base'}
  - {name: 'n_mgmt', value: '10.1.2.0/24', comment: 'n_mgmt'}
  - {name: 'n_dmz', value: '10.1.3.0/24', comment: 'n_dmz'}
  - {name: 'n_tools', value: '10.1.4.0/24', comment: 'n_tools'}
  - {name: 'n_clients', value: '10.1.5.0/24', comment: 'n_clients'}

  - {name: 'h_fw01', value: '10.1.2.2', comment: 'firewall 01'}
  - {name: 'h_fw02', value: '10.1.2.3', comment: 'firewall 02'}
  - {name: 'h_sw01', value: '10.1.2.4', comment: 'switch 01'}
  - {name: 'h_vt01', value: '10.1.2.11', comment: 'virtualization 01'}

  - {name: 'fp01', value: '10.1.3.15', comment: 'forward proxy 01'}
  - {name: 'rp01', value: '10.1.3.17', comment: 'reverse proxy 01'}
  - {name: 'ws01', value: '10.1.3.19', comment: 'web server 01'}
  - {name: 'mx01', value: '10.1.3.21', comment: 'mail server 01'}
  - {name: 'btc01', value: '10.1.3.23', comment: 'bitcoin server 01'}

  - {name: 'code01', value: '10.1.4.11', comment: 'code host 01'}

  - {name: 'nb01', value: '10.1.5.11', comment: 'notebook 01'}

freebsd_pf_filters_all:
  #-----------------------------------------------------------------------------
  # ICMP
  #-----------------------------------------------------------------------------

  # icmp from any to any
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'echoreq', comment: 'icmp echo request from any'}
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'echoreq', comment: 'icmp echo request to any'}
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'unreach', comment: 'icmp destination unreachable from any'}
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'unreach', comment: 'icmp destination unreachable to any'}
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'squench', comment: 'icmp source quench from any'}
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'squench', comment: 'icmp source quench to any'}

  #-----------------------------------------------------------------------------
  # SSH
  #-----------------------------------------------------------------------------

  # ssh from n_client
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$n_client'}, destinations: {'any'}, ports: {'22'}, comment: 'ssh from n_client'}

  #-----------------------------------------------------------------------------
  # DNS
  #-----------------------------------------------------------------------------

  # dns to h_fw01, h_fw02
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp', 'udp'}, sources: {'any'}, destinations: {'$h_fw01', '$h_fw02'}, ports: {'53'}, comment: 'dns to h_fw01, h_fw02'}

  #-----------------------------------------------------------------------------
  # NTP
  #-----------------------------------------------------------------------------

  # ntp to h_fw01, h_fw02
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'udp'}, sources: {'any'}, destinations: {'$h_fw01', '$h_fw02'}, ports: {'53'}, comment: 'ntp to h_fw01, h_fw02'}

  #-----------------------------------------------------------------------------
  # SMTP
  #-----------------------------------------------------------------------------

  # smtp to h_mx
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp'}, sources: {'any'}, destinations: {'$h_mx'}, ports: {'25'}, comment: 'smtp to h_mx'}

  #-----------------------------------------------------------------------------
  # SQUID
  #-----------------------------------------------------------------------------

  # squid to h_fproxy
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp'}, sources: {'any'}, destinations: {'$h_fp'}, ports: {'3128'} , comment: 'squid to h_fp'}

#-------------------------------------------------------------------------------
# OPENBSD_PF
#-------------------------------------------------------------------------------

openbsd_pf_macros_all:
  - {name: 'n_base', value: '10.1.1.0/24', comment: 'n_base'}
  - {name: 'n_mgmt', value: '10.1.2.0/24', comment: 'n_mgmt'}
  - {name: 'n_dmz', value: '10.1.3.0/24', comment: 'n_dmz'}
  - {name: 'n_tools', value: '10.1.4.0/24', comment: 'n_tools'}
  - {name: 'n_clients', value: '10.1.5.0/24', comment: 'n_clients'}

  - {name: 'h_fw01', value: '10.1.2.2', comment: 'firewall 01'}
  - {name: 'h_fw02', value: '10.1.2.3', comment: 'firewall 02'}
  - {name: 'h_sw01', value: '10.1.2.4', comment: 'switch 01'}
  - {name: 'h_vt01', value: '10.1.2.11', comment: 'virtualization 01'}

  - {name: 'fp01', value: '10.1.3.15', comment: 'forward proxy 01'}
  - {name: 'rp01', value: '10.1.3.17', comment: 'reverse proxy 01'}
  - {name: 'ws01', value: '10.1.3.19', comment: 'web server 01'}
  - {name: 'mx01', value: '10.1.3.21', comment: 'mail server 01'}
  - {name: 'btc01', value: '10.1.3.23', comment: 'bitcoin server 01'}

  - {name: 'code01', value: '10.1.4.11', comment: 'code host 01'}

  - {name: 'nb01', value: '10.1.5.11', comment: 'notebook 01'}

openbsd_pf_filters_all:

  #-----------------------------------------------------------------------------
  # ICMP
  #-----------------------------------------------------------------------------

  # icmp from any to any
  - {action: 'pass', quick: 'true', direction: 'in', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'echoreq', comment: 'icmp echo request from any'}
  - {action: 'pass', quick: 'true', direction: 'out', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'echoreq', comment: 'icmp echo request to any'}
  - {action: 'pass', quick: 'true', direction: 'in', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'unreach', comment: 'icmp destination unreachable from any'}
  - {action: 'pass', quick: 'true', direction: 'out', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'unreach', comment: 'icmp destination unreachable to any'}
  - {action: 'pass', quick: 'true', direction: 'in', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'squench', comment: 'icmp source quench from any'}
  - {action: 'pass', quick: 'true', direction: 'out', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'squench', comment: 'icmp source quench to any'}

  #-----------------------------------------------------------------------------
  # SSH
  #-----------------------------------------------------------------------------

  # ssh from n_client
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$n_client'}, destinations: {'any'}, ports: {'22'}, comment: 'ssh from n_client'}

  #-----------------------------------------------------------------------------
  # DNS
  #-----------------------------------------------------------------------------

  # dns to h_fw01, h_fw02
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp', 'udp'}, sources: {'any'}, destinations: {'$h_fw01', '$h_fw02'}, ports: {'53'}, comment: 'dns to h_fw01, h_fw02'}

  #-----------------------------------------------------------------------------
  # NTP
  #-----------------------------------------------------------------------------

  # ntp to h_fw01, h_fw02
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'udp'}, sources: {'any'}, destinations: {'$h_fw01', '$h_fw02'}, ports: {'53'}, comment: 'ntp to h_fw01, h_fw02'}

  #-----------------------------------------------------------------------------
  # SMTP
  #-----------------------------------------------------------------------------

  # smtp to h_mx
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp'}, sources: {'any'}, destinations: {'$h_mx'}, ports: {'25'}, comment: 'smtp to h_mx'}

  #-----------------------------------------------------------------------------
  # SQUID
  #-----------------------------------------------------------------------------

  # squid to h_fproxy
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp'}, sources: {'any'}, destinations: {'$h_fp'}, ports: {'3128'} , comment: 'squid to h_fp'}

#-------------------------------------------------------------------------------
# RESOLVER
#-------------------------------------------------------------------------------

resolver_domain: 'example.com'

resolver_nameserver:
  - {address: '10.1.2.11', comment: 'h_fw01'}
  - {address: '10.1.2.13', comment: 'h_fw02'}

resolver_search: ['example.com']

#-------------------------------------------------------------------------------
# SHELL
#-------------------------------------------------------------------------------

shell_ftp_proxy: 'http://fp.example.com:3128'

shell_http_proxy: 'http://fp.example.com:3128'

shell_https_proxy: 'http://fp.example.com:3128'

#-------------------------------------------------------------------------------
# SUDO
#-------------------------------------------------------------------------------

sudo_config_all:
  - name: 'root'
    state: 'true'
    order: '10'
    comment: 'root'
    config: |
      # root
      root ALL=(ALL) ALL

  - name: 'example'
    state: 'true'
    order: '50'
    config: |
      # example
      example ALL=(root) NOPASSWD: ALL
