---

#-------------------------------------------------------------------------------
# APACHE2
#-------------------------------------------------------------------------------

apache2_log_format_combined: 'remote_addr:%h %l remote_user:%u %t request:\"%r\" status:%>s %b \"%{Referer}i\" \"%{User-Agent}i\"'

apache2_log_format_combined_io: 'remote_addr:%h %l remote_user:%u %t request:\"%r\" status:%>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O'

apache2_log_format_combined_ssl: 'remote_addr:%h %l remote_user:%u %t request:\"%r\" status:%>s %b \"%{Referer}i\" \"%{User-agent}i\" %{SSL_PROTOCOL}x %{SSL_CIPHER}x'

apache2_log_format_common: 'remote_addr:%h %l remote_user:%u %t request:\"%r\" status:%>s %b'

apache2_monitor_monit_state: 'true'

#-------------------------------------------------------------------------------
# APT
#-------------------------------------------------------------------------------

apt_http_proxy: 'http://fp.example.com:3128'

apt_https_proxy: 'http://fp.example.com:3128'

apt_monitor_prom_state: 'true'

#-------------------------------------------------------------------------------
# AUDITD
#-------------------------------------------------------------------------------

auditd_config_all:
  - name: 'audit'
    state: 'true'
    config: |
      # First rule - delete all
      -D
      # Increase the buffers to survive stress events.
      -b 8192
      # Set failure mode to syslog
      -f 1
      # Log all commands (32-bit)
      -a exit,always -F arch=b32 -S execve -k auditcmd
      # Log all commands (64-bit)
      -a exit,always -F arch=b64 -S execve -k auditcmd
      # Enable auditd
      -e 1
      # Make config immutable - reboot required to change ruleset
      -e 2

auditd_monitor_monit_state: 'true'

#-------------------------------------------------------------------------------
# BASH
#-------------------------------------------------------------------------------

bash_tmout: 'disable'

#-------------------------------------------------------------------------------
# CHRONY
#-------------------------------------------------------------------------------

chrony_monitor_monit_state: 'true'

chrony_server:
  - {address: 'ntp01.example.com', options: {'burst', 'prefer', 'minpoll 4', 'maxpoll 6'}, comment: 'h_ntp01'}
  - {address: 'ntp02.example.com', options: {'burst', 'prefer', 'minpoll 4', 'maxpoll 6'}, comment: 'h_ntp02'}
  - {address: 'ntp03.example.com', options: {'burst', 'prefer', 'minpoll 4', 'maxpoll 6'}, comment: 'h_ntp03'}
  - {address: 'ntp04.example.com', options: {'burst', 'prefer', 'minpoll 4', 'maxpoll 6'}, comment: 'h_ntp04'}

#-------------------------------------------------------------------------------
# FSTRIM
#-------------------------------------------------------------------------------

fstrim_monitor_prom_state: 'true'

#-------------------------------------------------------------------------------
# GROUP
#-------------------------------------------------------------------------------

group_config_all:
  - {name: 'example', state: 'true', gid: '1000'}

#-------------------------------------------------------------------------------
# MARIADB
#-------------------------------------------------------------------------------

mariadb_monitor_monit_state: 'true'

#-------------------------------------------------------------------------------
# MONIT
#-------------------------------------------------------------------------------

monit_mail_server:
  - {address: '127.0.0.1', port: '25'}

monit_mail_to: []

#-------------------------------------------------------------------------------
# MONIT_EXPORTER
#-------------------------------------------------------------------------------

monit_exporter_monitor_monit_state: 'true'

#-------------------------------------------------------------------------------
# NANO
#-------------------------------------------------------------------------------

nano_state: 'remove'

#-------------------------------------------------------------------------------
# NFTABLES
#-------------------------------------------------------------------------------

nftables_filter_all:
  - {action: 'accept', direction: 'in', version: 'ipv4', protocol: 'icmp', code: 'destination-unreachable', comment: 'icmp destination-unreachable from any'}
  - {action: 'accept', direction: 'in', version: 'ipv4', protocol: 'icmp', code: 'echo-request', comment: 'icmp echo-request from any'}
  - {action: 'accept', direction: 'in', version: 'ipv4', protocol: 'icmp', code: 'parameter-problem', comment: 'icmp parameter-problem from any'}
  - {action: 'accept', direction: 'in', version: 'ipv4', protocol: 'icmp', code: 'source-quench', comment: 'icmp source-quench from any'}
  - {action: 'accept', direction: 'in', version: 'ipv4', protocol: 'icmp', code: 'time-exceeded', comment: 'icmp time-exceeded from any'}
  - {action: 'accept', direction: 'in', version: 'ipv4', protocol: 'tcp', sources: {'10.0.0.0/8'}, ports: {'22'}, comment: 'ssh from internal-networks'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'icmp', code: 'echo-request', comment: 'icmp echo-request to any'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'icmp', code: 'source-quench', comment: 'icmp source-quench to any'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.11', '10.0.0.12'}, ports: {'53'}, comment: 'dns to h_ns01, h_ns02'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'udp', destinations: {'10.0.0.11', '10.0.0.12'}, ports: {'53'}, comment: 'dns to h_ns01, h_ns02'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'udp', destinations: {'10.0.0.13', '10.0.0.14', '10.0.0.15', '10.0.0.16'}, ports: {'123'}, comment: 'ntp to h_ntp01, h_ntp02, h_ntp03, h_ntp04'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.17'}, ports: {'smtp'}, comment: 'smtp to h_mail'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', ports: {'10.0.0.18'}, comment: 'squid to h_proxy'}

#-------------------------------------------------------------------------------
# NGINX
#-------------------------------------------------------------------------------

nginx_log_format_main: |-
  'remote_addr:$remote_addr - $remote_user [$time_local] request:"$request" '
  'status:$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" http_x_forwarded_for:"$http_x_forwarded_for"'

nginx_log_format_main_ssl: |-
  'remote_addr:$remote_addr - $remote_user [$time_local] request:"$request" '
  'status:$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" http_x_forwarded_for:"$http_x_forwarded_for" '
  '$ssl_protocol/$ssl_cipher '

nginx_monitor_monit_state: 'true'

#-------------------------------------------------------------------------------
# NODE_EXPORTER
#-------------------------------------------------------------------------------

node_exporter_monitor_monit_state: 'true'

#-------------------------------------------------------------------------------
# OPENNTPD
#-------------------------------------------------------------------------------

openntpd_monitor_mail_from_address: 'root@example.com'

openntpd_monitor_mail_to_address: ['admin@example.com']

openntpd_monitor_mail_state: 'true'

openntpd_monitor_monit_state: 'true'

openntpd_server:
  - {address: 'ntp01.example.com', comment: 'h_ntp01'}
  - {address: 'ntp02.example.com', comment: 'h_ntp02'}
  - {address: 'ntp03.example.com', comment: 'h_ntp03'}
  - {address: 'ntp04.example.com', comment: 'h_ntp04'}

#-------------------------------------------------------------------------------
# OPENSMTPD
#-------------------------------------------------------------------------------

opensmtpd_accept_all: |
  # Accept: Aliases
  accept for local alias <aliases> deliver to mbox
  # Accept: Relay
  accept for any relay via smtp://mail.example.com

opensmtpd_monitor_monit_state: 'true'

#-------------------------------------------------------------------------------
# OPENSSH
#-------------------------------------------------------------------------------

openssh_allow_users: ['example']

openssh_monitor_monit_state: 'true'

openssh_password_authentication: 'no'

#-------------------------------------------------------------------------------
# RESOLVER
#-------------------------------------------------------------------------------

resolver_domain: 'example.com'

resolver_nameserver: 
  - {address: '10.0.0.11', comment: 'Server: h_ns01'}
  - {address: '10.0.0.12', comment: 'Server: h_ns02'}

resolver_search: ['example.com']

#-------------------------------------------------------------------------------
# RESTIC
#-------------------------------------------------------------------------------

restic_keep_daily: 30

restic_keep_hourly: 168

restic_keep_monthly: 240

restic_keep_weekly: 12

restic_monitor_mail_from_address: 'root@example.com'

restic_monitor_mail_to_address: ['user@example.com']

restic_monitor_mail_state: 'true'

restic_monitor_prom_state: 'true'

restic_password: '7rMu,ntxrEfd+RFAQdcJh+US.Cu2XQF.'

restic_server_address: 'bs.example.com'

restic_server_password: '8cgT97AiwCVfw5G4kt_ANHGBbrvFjrRP'

#-------------------------------------------------------------------------------
# ROOT
#-------------------------------------------------------------------------------

root_password: '$2b$10$Jua/9rgOstNEVRKz11ncGO1EG.Z1krMLkOurJe4jNHVEU0UZV4fI6'

#-------------------------------------------------------------------------------
# RSYSLOG
#-------------------------------------------------------------------------------

rsyslog_monitor_monit_state: 'true'

#-------------------------------------------------------------------------------
# SHELL
#-------------------------------------------------------------------------------

shell_ftp_proxy: 'http://fp.example.com:3128'

shell_http_proxy: 'http://fp.example.com:3128'

shell_https_proxy: 'http://fp.example.com:3128'

shell_no_proxy: ['localhost', '127.0.0.1', '::1', 'bs.example.com', 'backup.example.com']

#-------------------------------------------------------------------------------
# SUDO
#-------------------------------------------------------------------------------

sudo_config_all:
  - name: 'root'
    state: 'true'
    order: '10'
    config: |
      # root
      root ALL=(ALL) ALL

  - name: 'example'
    state: 'true'
    order: '50'
    config: |
      # example
      example ALL=(root) NOPASSWD: ALL

#-------------------------------------------------------------------------------
# TIMEZONE
#-------------------------------------------------------------------------------

timezone_timezone: 'Europe/Zurich'

#-------------------------------------------------------------------------------
# USER
#-------------------------------------------------------------------------------

user_config_all:
  - name: 'example'
    state: 'true'
    comment: 'example'
    uid: '1000'
    group: 'example'
    groups: ['wheel']
    groups_append: 'true'
    password: '$2b$10$6cmx3Y2CaKFoAwqWmKXxtOCD0FWgPZ.QWor2m9W8U.m5E7ygTCb..'
    password_update: 'true'
    shell: '/bin/bash'
    authorized_key:
      - state: 'true'
        key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDR/DO2YFGGs7Qle7Dt2pxsqveVsiXeHVZd2vpjSqKFd7psEZ53BOmAdRoaK/VZvuj+RPjmfJCYDKAxoVxCIL9l2hkfv35e6YRDT0gh0wely37zIFrOineyufYEIOVtgHKKjr88ZP641z9oLgT7xNPKNqhTat5sOdB5cAEf+0q8uFLzcBEdQpTePQmigl4Cp7RL3YHtEDXfDRqlNiAsCd5/YKabDW1rVMksbGQSynOrFyjtkQw5Th+xUZe7uBU08wQEFWXGJacbCEME568UBzbOoqbsuxvD41QggGOI3CQC1QPtXUweFFtc0iwxfwSX4IpTuqIa/7RJRepzPpOf8PsHj135h1SYXZ5fxtnL2/yTfwmaCJb7iUqpJzfyJyndLgdbCtB/JccOUWxSBkA+hU4UVZS5AVN/n+oyGGB7hKt6vk2xRwV47iV+HPdcbaGPqxBOynpAKtWEtMXFxOa/rCh0i9ZDAkj7wxPaje8nbNdQS8O5yrLquXIwOSwyeyKN2yDFGRSiD3In+BilqbmA8N8o/2ZaRKSjjmH7Jpm+F+AR9lAi3M8aj4Ic444/zKO4EbzntyumzG59FPTO3KS67JemixJelKIJMFnOwSpoLMOSfpnVS0LTdVy3mkwQjwEgFXZtMeg4F3o0AO80E5/sjR9sd4zMTLwJHCO+tQVgQzSGYw== example@example.com'
