---

#-------------------------------------------------------------------------------
# ALERTMANAGER
#-------------------------------------------------------------------------------

alertmanager_config:
  - section: 'global'
    config: |
      smtp_from: 'ms@example.com'
      smtp_hello: 'ms.example.com'
      smtp_smarthost: 'mail.example.com:25'
      smtp_auth_username: ''
      smtp_auth_password: ''
      smtp_require_tls: false

  - section: 'route'
    config: |
      receiver: 'user'
      group_by: ['instance', 'alert']
      group_wait: 1m
      group_interval: 30m
      repeat_interval: 150m
      routes:
      - match:
          severity: 'critical'
        receiver: 'user'

  - section: 'inhibit_rules'
    config: |
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname']

  - section: 'receivers'
    config: |
      - name: 'user'
        email_configs:
        - to: 'user@example.com'

alertmanager_monitor_monit_state: 'true'

#-------------------------------------------------------------------------------
# BLACKBOX_EXPORTER
#-------------------------------------------------------------------------------

blackbox_exporter_monitor_monit_state: 'true'

#-------------------------------------------------------------------------------
# GRAFANA
#-------------------------------------------------------------------------------

grafana_monitor_monit_state: 'true'

grafana_smtp_from_address: 'ms@example.com'

grafana_smtp_from_name: 'ms'

grafana_smtp_host: 'mail.example.com'

grafana_smtp_port: '25'

grafana_smtp_state: 'true'

#-------------------------------------------------------------------------------
# MOTD
#-------------------------------------------------------------------------------

motd_host_description: 'Monitoring Server'

#-------------------------------------------------------------------------------
# NGINX
#-------------------------------------------------------------------------------

nginx_config:
  - name: 'alert.example.com'
    state: 'true'
    port: 80
    hsts_state: 'true'
    xss_protection_state: 'true'
    config: |
      return 301 https://$server_name$request_uri;

  - name: 'alert.example.com'
    state: 'true'
    port: 443
    hsts_state: 'true'
    xss_protection_state: 'true'
    ssl_state: 'true'
    ssl_ecdh_curve: 'secp384r1'
    ssl_certificate: '/etc/ssl/example/wildcard.example.com.crt'
    ssl_certificate_key: '/etc/ssl/example/wildcard.example.com.pem'
    config: |
      location / {
        proxy_pass                         http://localhost:9093/;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

  - name: 'mon.example.com'
    alias: ['monitor.example.com']
    state: 'true'
    port: 80
    hsts_state: 'true'
    xss_protection_state: 'true'
    config: |
      return 301 https://$server_name$request_uri;

  - name: 'mon.example.com'
    alias: ['monitor.example.com']
    state: 'true'
    port: 443
    hsts_state: 'true'
    xss_protection_state: 'true'
    ssl_state: 'true'
    ssl_ecdh_curve: 'secp384r1'
    ssl_certificate: '/etc/ssl/example/wildcard.example.com.crt'
    ssl_certificate_key: '/etc/ssl/example/wildcard.example.com.pem'
    config: |
      location / {
        proxy_pass                         http://localhost:3000/;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

  - name: 'metric.example.com'
    state: 'true'
    port: 80
    hsts_state: 'true'
    xss_protection_state: 'true'
    config: |
      return 301 https://$server_name$request_uri;

  - name: 'metric.example.com'
    state: 'true'
    port: 443
    hsts_state: 'true'
    xss_protection_state: 'true'
    ssl_state: 'true'
    ssl_ecdh_curve: 'secp384r1'
    ssl_certificate: '/etc/ssl/example/wildcard.example.com.crt'
    ssl_certificate_key: '/etc/ssl/example/wildcard.example.com.pem'
    config: |
      location / {
        proxy_pass                         http://localhost:9090/;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

#-------------------------------------------------------------------------------
# NFTABLES
#-------------------------------------------------------------------------------

nftables_filter_host:
  - {action: 'accept', direction: 'in', version: 'ipv4', protocol: 'tcp', sources: {'10.1.3.0/24', '10.1.5.0/24'}, ports: {'80', '443'}, comment: 'http, https from n_dmz, n_clients'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', ports: {'80', '443'}, comment: 'http, https to any (blackbox_exporter)'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'9100'}, comment: 'node_exporter to internal-networks'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'9101'}, comment: 'haproxy_exporter to internal-networks'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'9104'}, comment: 'mysqld_exporter to internal-networks'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'9115'}, comment: 'blackbox_exporter to internal-networks'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'9388'}, comment: 'monit_exporter to internal-networks'}

#-------------------------------------------------------------------------------
# PROMETHEUS
#-------------------------------------------------------------------------------

prometheus_alertmanager_url: 'https://alert.example.com'

prometheus_grafana_url: 'https://mon.example.com'

prometheus_prometheus_url: 'https://metric.example.com'

prometheus_blackbox_exporter_http_ip4_basic_manual_hosts:
  - {address: 'https://web.example.com', hostname: 'web'}
  - {address: 'https://wiki.example.com', hostname: 'wiki'}

prometheus_blackbox_exporter_icmp_ip4_manual_hosts:
  - {address: '10.1.1.11', hostname: 'fp01'}
  - {address: '10.1.2.2', hostname: 'fw01'}
  - {address: '10.1.2.3', hostname: 'fw02'}
  - {address: '10.1.3.11', hostname: 'ns01'}
  - {address: '10.1.3.15', hostname: 'ws01'}

prometheus_monitor_monit_state: 'true'

prometheus_node_exporter_target_manual_hosts:
  - {address: '10.1.1.11', hostname: 'fp01'}
  - {address: '10.1.2.2', hostname: 'fw01'}
  - {address: '10.1.2.3', hostname: 'fw02'}
  - {address: '10.1.3.11', hostname: 'ns01'}
  - {address: '10.1.3.15', hostname: 'ws01'}

prometheus_smokeping_prober_state: 'true'

#-------------------------------------------------------------------------------
# RESTIC
#-------------------------------------------------------------------------------

restic_state: 'remove'

#-------------------------------------------------------------------------------
# RSYSLOG
#-------------------------------------------------------------------------------

rsyslog_config_host:
  - name: nginx
    comment: Nginx
    section: input
    config:
      - {type: imfile, File: '/var/log/nginx/*_access.log', Tag: nginx, Severity: info, Facility: local6}
      - {type: imfile, File: '/var/log/nginx/*_error.log', Tag: nginx, Severity: info, Facility: local6}

#-------------------------------------------------------------------------------
# SMOKEPING_PROBER
#-------------------------------------------------------------------------------

smokeping_prober_hosts:
  - 'localhost'

smokeping_prober_monitor_monit_state: 'true'
