---

# APACHE2

apache2_global_config: |
  # Configures the OCSP stapling cache
  SSLStaplingCache "shmcb:logs/stapling-cache(150000)"

apache2_config:
  - name: 'example.com'
    alias: ['web.example.com', 'www.example.com']
    state: 'true'
    port: '80'
    server_admin: 'admin@example.com'
    document_root: '/var/www/html'
    xss_protection_state: 'true'
    config: |
      Redirect permanent /  https://example.com/

  - name: 'example.com'
    alias: ['web.example.com', 'www.example.com']
    state: 'true'
    port: '443'
    server_admin: 'admin@example.com'
    document_root: '/var/www/html'
    xss_protection_state: 'true'
    ssl_state: 'true'
    ssl_certificate: '/etc/letsencrypt/live/example.com/cert.pem'
    ssl_certificate_key: '/etc/letsencrypt/live/example.com/privkey.pem'
    ssl_certificate_chain: '/etc/letsencrypt/live/example.com/chain.pem'
    config: |
      SSLUseStapling  On
      SSLOCSPProxyURL "http://fp.example.com:3128/"

      SSLProxyEngine On

      <Location "/">
        ProxyPass        "https://example.com/"
        ProxyPassReverse "https://example.com/"
      </Location>

# MODSECURITY

modsecurity_sec_rule_engine: 'enable'

# MODSECURITY_CRS

modsecurity_crs_sec_default_action:
  - "phase:1,log,auditlog,redirect:'http://%{request_headers.host}/',tag:'Host: %{request_headers.host}'"
  - "phase:2,log,auditlog,redirect:'http://%{request_headers.host}/',tag:'Host: %{request_headers.host}'"

# MOTD

motd_host_description: 'Reverse Proxy'

# NFTABLES

nftables_filter_host:
  - {action: 'accept', direction: 'in', version: 'ipv4', protocol: 'tcp', ports: {'80', '443'}, comment: 'http, https from any'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.1.2.0/24', '10.1.3.0/24', '10.1.4.0/24'}, ports: {'80', '443'}, comment: 'http, https to n_mgmt, n_dmz, n_tools'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', ports: {'443'}, comment: 'https to any (letsencrypt)'}

# RSYSLOG

rsyslog_config_host:
  - name: "apache2"
    comment: "Apache HTTPD"
    section: "input"
    config:
      - {type: imfile, File: '/var/log/apache2/*access_log', Tag: apache2, Severity: info, Facility: local6}
      - {type: imfile, File: '/var/log/apache2/*error_log', Tag: apache2, Severity: info, Facility: local6}
