---

#-------------------------------------------------------------------------------
# ALL
#-------------------------------------------------------------------------------

# Bootstrap
- hosts: all
  tasks:
    - name: group create 'ansible_distribution_version'
      group_by:
        key: "{{ansible_distribution_version}}"

- hosts: '3.7.0'
  become: 'yes'
  gather_facts: False
  roles:
    - role: apk

- hosts: '3.8.0'
  become: 'yes'
  gather_facts: False
  roles:
    - role: apk

# Pre
- hosts: all
  become: 'yes'
  roles:
    - role: shell
    - role: bash
# TODO: Create Ansible role
#   - role: user

# Main
- hosts: all
  become: 'yes'
  roles:
# TODO: Create Ansible role
#   - role: auditd
    - role: bind_tools
    - role: busybox_ntpd
    - role: common
    - role: coreutils
    - role: diffutils
    - role: file
    - role: findutils
    - role: fstab
    - role: gnu_grep
    - role: gnu_sed
    - role: hostname
    - role: hosts
    - role: htop
    - role: iftop
    - role: inittab
    - role: issue
    - role: less
# TODO: Create Ansible role
#   - role: locale
    - role: lsof
    - role: motd
    - role: nano
    - role: openbsd_netcat
    - role: opensmtpd
    - role: openssh
    - role: resolver
# TODO: Create Ansible role
#   - role: root
    - role: rsync
    - role: sudo
    - role: sysctl
    - role: tcpdump
# TODO: Create Ansible role
#   - role: timezone
    - role: tmux
    - role: unzip
    - role: vim
    - role: wget
    - role: zip

# Post
- hosts: all
  become: 'yes'
  roles:
# TODO: Create Ansible role
#   - role: iptables
