---

#-------------------------------------------------------------------------------
# REVERSE PROXY
#-------------------------------------------------------------------------------

- hosts: rp
  become: 'yes'
  roles:
    - role: httpd
    - role: mod_security
    - role: mod_security_crs
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'
