---

#-------------------------------------------------------------------------------
# MOTD
#-------------------------------------------------------------------------------

motd_host_description: 'Forward Proxy'

#-------------------------------------------------------------------------------
# OPENBSD_PF
#-------------------------------------------------------------------------------

openbsd_pf_filters_host:
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$n_dmz', '$n_int'}, destinations: {'any'}, ports: {'3128'}, state: '$default_tcp', comment: 'HTTP(S): From n_dmz, n_int'}
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp'}, sources: {'any'}, destinations: {'any'}, ports: {'http', 'https'}, state: '$default_tcp', comment: 'HTTP(S): To any'}
