---

#-------------------------------------------------------------------------------
# MONIT
#-------------------------------------------------------------------------------

monit_config_host:
  - name: 'squid'
    state: 'true'
    comment: 'Squid'
    config: |
      check process squid with pidfile "/var/run/squid.pid"
        start program = "/usr/sbin/rcctl start squid"
        stop program  = "/usr/sbin/rcctl stop squid"
        if failed host 127.0.0.1 port 3128 type tcp with timeout 10 seconds then alert
        if 5 restarts within 5 cycles then timeout

#-------------------------------------------------------------------------------
# MOTD
#-------------------------------------------------------------------------------

motd_host_description: 'Forward Proxy'

#-------------------------------------------------------------------------------
# OPENBSD_PF
#-------------------------------------------------------------------------------

openbsd_pf_filters_host:
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$n_base', '$n_mgmt', '$n_dmz', '$n_tools', '$n_clients'}, destinations: {'any'}, ports: {'3128'}, comment: 'squid from n_base, n_mgmt, n_dmz, n_tools, n_clients'}
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp'}, sources: {'any'}, destinations: {'any'}, ports: {'80', '443'}, comment: 'http, https to any'}

#-------------------------------------------------------------------------------
# SQUID
#-------------------------------------------------------------------------------

squid_acl:
  - {name: 'src_network_base', type: 'src', value: '10.1.1.0/24', comment: 'n_base'}
  - {name: 'src_network_mgmt', type: 'src', value: '10.1.2.0/24', comment: 'n_mgmt'}
  - {name: 'src_network_dmz', type: 'src', value: '10.1.3.0/24', comment: 'n_dmz'}
  - {name: 'src_network_tools', type: 'src', value: '10.1.4.0/24', comment: 'n_tools'}
  - {name: 'src_network_client', type: 'src', value: '10.1.5.0/24', comment: 'n_client'}

squid_http_access:
  # n_base
  - {action: 'allow', source: 'src_network_base', protocol: 'http', destination: 'dst_domain_allowed', comment: 'n_base'}
  - {action: 'allow', source: 'src_network_base', protocol: 'https SSL_ports', destination: 'dst_domain_allowed', comment: 'n_base'}
  - {action: 'allow', source: 'src_network_base', protocol: 'http', destination: 'dst_network_allowed', comment: 'n_base'}
  - {action: 'allow', source: 'src_network_base', protocol: 'https SSL_ports', destination: 'dst_network_allowed', comment: 'n_base'}

  # n_mgmt
  - {action: 'allow', source: 'src_network_mgmt', protocol: 'http', destination: 'dst_domain_allowed', comment: 'n_mgmt'}
  - {action: 'allow', source: 'src_network_mgmt', protocol: 'https SSL_ports', destination: 'dst_domain_allowed', comment: 'n_mgmt'}
  - {action: 'allow', source: 'src_network_mgmt', protocol: 'http', destination: 'dst_network_allowed', comment: 'n_mgmt'}
  - {action: 'allow', source: 'src_network_mgmt', protocol: 'https SSL_ports', destination: 'dst_network_allowed', comment: 'n_mgmt'}

  # n_dmz
  - {action: 'allow', source: 'src_network_dmz', protocol: 'http', destination: 'dst_domain_allowed', comment: 'n_dmz'}
  - {action: 'allow', source: 'src_network_dmz', protocol: 'https SSL_ports', destination: 'dst_domain_allowed', comment: 'n_dmz'}
  - {action: 'allow', source: 'src_network_dmz', protocol: 'http', destination: 'dst_network_allowed', comment: 'n_dmz'}
  - {action: 'allow', source: 'src_network_dmz', protocol: 'https SSL_ports', destination: 'dst_network_allowed', comment: 'n_dmz'}

  # n_tools
  - {action: 'allow', source: 'src_network_tools', protocol: 'http', destination: 'dst_domain_allowed', comment: 'n_tools'}
  - {action: 'allow', source: 'src_network_tools', protocol: 'https SSL_ports', destination: 'dst_domain_allowed', comment: 'n_tools'}
  - {action: 'allow', source: 'src_network_tools', protocol: 'http', destination: 'dst_network_allowed', comment: 'n_tools'}
  - {action: 'allow', source: 'src_network_tools', protocol: 'https SSL_ports', destination: 'dst_network_allowed', comment: 'n_tools'}

  # n_clients
  - {action: 'allow', source: 'src_network_clients', protocol: 'http', destination: 'dst_domain_allowed', comment: 'n_clients'}
  - {action: 'allow', source: 'src_network_clients', protocol: 'https SSL_ports', destination: 'dst_domain_allowed', comment: 'n_clients'}
  - {action: 'allow', source: 'src_network_clients', protocol: 'http', destination: 'dst_network_allowed', comment: 'n_clients'}
  - {action: 'allow', source: 'src_network_clients', protocol: 'https SSL_ports', destination: 'dst_network_allowed', comment: 'n_clients'}

squid_domain_allowed:
  # OpenBSD
  - {name: 'ftp.openbsd.org', comment: 'OpenBSD: Updates'}
  - {name: 'ftp.eu.openbsd.org', comment: 'OpenBSD: Updates'}
  - {name: 'ftp2.eu.openbsd.org', comment: 'OpenBSD: Updates'}
  - {name: 'cdn.openbsd.org', comment: 'OpenBSD: Updates'}
  - {name: 'firmware.openbsd.org', comment: 'OpenBSD: Updates'}

  # CentOS
  - {name: 'mirror.centos.org', comment: 'CentOS: Updates'}
  - {name: 'vault.centos.org', comment: 'CentOS: Updates'}
  - {name: 'mirrors.kernel.org', comment: 'CentOS: Updates'}

  # Debian
  - {name: 'security.debian.org', comment: 'Debian updates'}
  - {name: 'security-cdn.debian.org', comment: 'Debian updates'}
  - {name: 'cdn-fastly.deb.debian.org', comment: 'Debian updates'}
  - {name: 'ftp.ch.debian.org', comment: 'Debian updates'}

  # Proxmox
  - {name: 'download.proxmox.com', comment: 'Proxmox updates'}
  - {name: 'enterprise.proxmox.com', comment: 'Proxmox updates'}

  # Bitcoin
  - {name: 'bitcoin.org', comment: 'Bitcoin releases'}
