---

#-------------------------------------------------------------------------------
# MONIT
#-------------------------------------------------------------------------------

monit_config_host:
  - name: 'nginx'
    state: 'true'
    comment: 'Nginx'
    config: |
      check process nginx with pidfile "/var/run/nginx.pid"
        start program = "/usr/sbin/rcctl start nginx"
        stop program  = "/usr/sbin/rcctl stop nginx"
        if failed host 127.0.0.1 port 80 type tcp with timeout 10 seconds then alert
        if 5 restarts within 5 cycles then timeout

#-------------------------------------------------------------------------------
# MOTD
#-------------------------------------------------------------------------------

motd_host_description: 'Web Server'

#-------------------------------------------------------------------------------
# OPENBSD_PF
#-------------------------------------------------------------------------------

openbsd_pf_filters_host:
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$h_rp', '$n_clients'}, destinations: {'any'}, ports: {'80', '443'}, comment: 'http, https from h_rp, n_clients'}
