---

#-------------------------------------------------------------------------------
# ALL
#-------------------------------------------------------------------------------

# Bootstrap
- hosts: all
  tasks:
    - name: group create 'ansible_distribution'
      group_by:
        key: "{{ansible_distribution}}"

- hosts: FreeBSD
  become: yes
  gather_facts: False
  roles:
    - role: freebsd_pkg
    - role: freebsd_rc
    - role: freebsd_periodic
    - role: root
    - role: user
    - role: monit
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

- hosts: OpenBSD
  become: yes
  gather_facts: False
  roles:
    - role: openbsd_syspatch
    - role: openbsd_rc
    - role: openbsd_periodic
    - role: root
    - role: user
    - role: monit
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

# Pre
- hosts: all
  become: yes
  roles:
    - role: shell
    - role: bash
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

# Main
- hosts: all
  become: yes
  roles:
    - role: bind_tools
    - role: colordiff
    - role: coreutils
    - role: cron
    - role: denyhosts
    - role: file
    - role: findutils
    - role: freecolor
    - role: gnu_diff
    - role: gnu_grep
    - role: gnu_netcat
    - role: gnu_sed
    - role: gnu_watch
    - role: gnu_zip
    - role: hosts
    - role: hostname
    - role: hostname_if
    - role: htop
    - role: ifstat
    - role: iftop
    - role: less
    - role: lsof
    - role: mailx
    - role: motd
    - role: nano
    - role: netcat
    - role: openntpd
    - role: opensmtpd
    - role: openssh
    - role: passwd
    - role: resolver
    - role: rsync
    - role: sudo
    - role: tcpdump
    - role: tmux
    - role: unzip
    - role: vim
    - role: wget
    - role: zip
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

# Post
- hosts: all
  become: yes
  roles:
    - role: freebsd_pf
    - role: openbsd_pf
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'
