---

# PRE

- hosts: all
  become: True
  roles:
    - role: hosts
    - role: apt
    - role: package
    - role: shell
    - role: bash
    - role: sudo
    - role: user
    - role: ca_certificate
  environment:
    http_proxy: 'http://proxy.example.com:3128'
    https_proxy: 'http://proxy.example.com:3128'
    ftp_proxy: 'http://proxy.example.com:3128'

# MAIN

- hosts: all
  become: True
  roles:
    - role: auditd
    - role: chrony
    - role: fstrim
    - role: hostname
    - role: issue
    - role: locale
    - role: motd
    - role: network
    - role: node_exporter
    - role: opensmtpd
    - role: openssh
    - role: pve
    - role: resolver
    - role: root
    - role: rsyslog
    - role: sysctl
    - role: systemd
    - role: timezone
    - role: tmux
    - role: vim
    - role: zfs
  environment:
    http_proxy: 'http://proxy.example.com:3128'
    https_proxy: 'http://proxy.example.com:3128'
    ftp_proxy: 'http://proxy.example.com:3128'

# POST

- hosts: all
  become: True
  roles:
    - role: monit
    - role: monit_exporter
    - role: nftables
  environment:
    http_proxy: 'http://proxy.example.com:3128'
    https_proxy: 'http://proxy.example.com:3128'
    ftp_proxy: 'http://proxy.example.com:3128'
