---

#-------------------------------------------------------------------------------
# ALL
#-------------------------------------------------------------------------------

# Bootstrap
- hosts: all
  tasks:
    - name: group create 'ansible_distribution'
      group_by:
        key: "{{ansible_distribution}}"

- hosts: '10'
  become: 'yes'
  gather_facts: False
  roles:
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

# Pre
- hosts: all
  become: yes
  roles:
    - role: shell
    - role: bash
    - role: user
    - role: apt
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

# Main
- hosts: all
  become: yes
  roles:
    - role: auditd
    - role: colordiff
    - role: dstat
    - role: gnu_awk
    - role: gnu_grep
    - role: gnu_sed
    - role: hostname
    - role: hosts
    - role: htop
    - role: iproute2
    - role: issue
    - role: less
    - role: locale
    - role: monit
    - role: motd
    - role: net_tools
    - role: node_exporter
    - role: openssh
    - role: openvswitch_switch
    - role: pve
    - role: resolver
    - role: root
    - role: rsyslog
    - role: sudo
    - role: sysctl
    - role: sysstat
    - role: systemd
    - role: systemd_timesyncd
    - role: timezone
    - role: tmux
    - role: vim
    - role: zfs
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

# Post
- hosts: all
  become: yes
  roles:
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'
