---

# BASH

bash_tmout: ''

# CA_CERTIFICATE

ca_certificate_config:
  - name: 'ca.example.com.crt'
    state: True
    content: |
      -----BEGIN CERTIFICATE-----
      MIIKWTCCBkGgAwIBAgIUVp2gpuBisK+mTHwq/7fK52XELn0wDQYJKoZIhvcNAQEL
      BQAwgZoxCzAJBgNVBAYTAkNDMRQwEgYDVQQIDAtjeWJlciBzdGF0ZTETMBEGA1UE
      BwwKY3liZXIgY2l0eTEQMA4GA1UECgwHZXhhbXBsZTETMBEGA1UECwwKY3liZXIg
      dGVhbTEXMBUGA1UEAwwOY2EuZXhhbXBsZS5jb20xIDAeBgkqhkiG9w0BCQEWEWFk
      bWluQGV4YW1wbGUuY29tMB4XDTI0MDEyMTEzMzU1OFoXDTM0MDExODEzMzU1OFow
      gZoxCzAJBgNVBAYTAkNDMRQwEgYDVQQIDAtjeWJlciBzdGF0ZTETMBEGA1UEBwwK
      Y3liZXIgY2l0eTEQMA4GA1UECgwHZXhhbXBsZTETMBEGA1UECwwKY3liZXIgdGVh
      bTEXMBUGA1UEAwwOY2EuZXhhbXBsZS5jb20xIDAeBgkqhkiG9w0BCQEWEWFkbWlu
      QGV4YW1wbGUuY29tMIIEIjANBgkqhkiG9w0BAQEFAAOCBA8AMIIECgKCBAEAmJfe
      pqpFjTpQNCDMMELNC7kmhPCCGqvbJepfXMM4AwkCv40L4jsQqo6eZZu6LQJzEjbc
      S1iCJtUksy7NUPp0+i2xCqN8gqtDgaWGTJq4thTUrEUOVxuRFirAncSCIARdtE/F
      t4AitFZkxXCfoJ+9KMxyOvhmtMXuA5YRKCfto8V+iEihzbN5176NtZBmzB+tZqJW
      uSp+IgnTtuKOki/Exanqn3UmgRw73f6kjpTonmjpCyTA+PGaVYrCqOa90okLu1ky
      r0uvc3pSgJ7zKSFBo7YjX6KnOeiZGbbmrykB6hPNA8MBfbz5Miwwy7KCPkU720No
      anCbWf3TtG4oxhm6qnD8IZUivtlHW8/vP/ZsUA/Ew6M5oltZBAn+my934MBhLhfb
      6MK6hRSRGOIy7b2taTeLyhtzLFAUCku7ZT10r+CZNtwkeWG/JAeVCP5Cn1CaGUKe
      rnkHB/BL4T169dQioTMEQzyUxEvj9SdqJqwpjAxbOOesm9Qw0mYra+NSSv3U9125
      jiOEADB1mS6yfv6DCAJCZl/VTkl++Ik1fC7wZApGFepHf1BMCGwddcsTu5a0zBwm
      eXmxxbuTwbUYV4ANAWWA3gRbCnrqsM3BrUfjC1EdT4n2DJjjTRTm2HDjx3FqVEIY
      hBvzG0ivbv7zWz4uzUeTvHE2dnw7B38f5NJYfIMfSHJQetQerULgkCtTw6r9aSjN
      RdtO+uFHw+EWYhBoZTHAAHUJaECtmDC6cjYX1dBO4LaIPhcTE0jvtOk84csqT0qZ
      lxiGjWcJXKQ8ALtExF8bxr9nhacJ45o2ks6UcH+DgtOByJA/IaMlpMClgiCUlD20
      Yiy5fqa5XsQCp7lZlIZzOAGxgpnZAwwcGrQPupGxy08OX/wKocp3jgeN4w66a0dN
      9Fka1/qeAIloE0U0yw94hYn3aw5EpfGHeu/WtwuTyOrDK99OLkQy9t99DlfM83Pn
      oqa2xLmkia3IVTRuEqscNiUr4IURfcFSAUDKVroAN1K37ouBbq+WncXms5s+aP10
      p8UkfhROITY4BJvukYAko7pRfkFesW+PaPBU2RDqeqjezi4qwEJJetdXYJLScgVS
      wu+boAv9SyZeBuDvnQ8yVtFuLIUgh3k6lgECF0vrLCIETDoT/0u8rwA9fexhozOo
      w6GUiLgJfZwCEPV/+RVHgEe3AkP4zjXQ6J1Sc/jvUeXmx464RTIpiImKhwGCEUVC
      290isDUABIMshj6PRYRKX4buROWFTR0vV8qN1mYU9ldYcoLX/LZvRyuNGSMaNoZP
      cvR8ai+j0F9tTuonHvTgeLmZ7ybg7EG/pMzpWTMZObrQ15zO82iCaEW+BQbKzBEv
      IulouwBmUDyxcTgGcwIDAQABo4GUMIGRMB0GA1UdDgQWBBR7doTK3AiyLCVsQAwG
      odksvJ4/jTAfBgNVHSMEGDAWgBR7doTK3AiyLCVsQAwGodksvJ4/jTAPBgNVHRMB
      Af8EBTADAQH/MA4GA1UdDwEB/wQEAwIBhjAuBgNVHR8EJzAlMCOgIaAfhh1odHRw
      Oi8vY3JsLmV4YW1wbGUuY29tL2NhLmNybDANBgkqhkiG9w0BAQsFAAOCBAEASckR
      YLadLAngdgJWfwKHhnHo05ua+Uoiw7YObZuuTj+xhZsnEqagzdt0BmukxPPwfA4J
      gzp64AL/XJk8EDQLlZCz6g+Qq194KXl9outQ0q9wK5ZRyk1b2R4IU7A8Z8m3U7gT
      Fzia2YLJKwwsatz+R6iLnq4MNIAUPZlyG9jIUOYUEHfb8v4JPNSiJO8lcqliS3nR
      lQPUzZO1n6XNgdEClcxw2D5ZLEL9XoqM60MgL55A1qFZzhHrTQpjeegoGjNKAb8E
      MvK89yFbNyaB4aMfKceGvZ2Of0F0/vdxZ55dIz2SiwP81ttPX0ORSw8CWqAYHI/1
      wthxAUvV7YEdvaCbskId9Q6mBztSy6cb3ZKO9VJSNAzc4bgAsmnwRRR5c2DIf8x/
      QMdB+mt99ESiCeTJ9dwWUBSK5Evdt8rE0TQni1WypChqM1R+YZ4JMWEwymYiv6L+
      2JkRbNXjOO22Yl6NQClu1dVgBDksWMV3m/mcYI5mTfZVua05XawrPiWl95ppbBrR
      fwXZ3E5Ncn8BFGKx1PqYEsjcpjhl0TPRwCunD1eijxKhusmrhW22Bv9DqWQBdWqa
      AANQR+GEadl6w3fyi+3dC042f/TGpZV+PpMp4cAjdf1YSZFZV9eglaO+LArwriBu
      wYCRzYmAEfY8NxAWtnpziIfltBNtFVvseGka9LiySiEh8x3e2EJ8KZweTNHlZyHZ
      MeBpc/wWrtBnVjEvi/nqXY6ZSwMqig3Bt60xtAUtafVlqS4hiH+WAbH4V0iRHKG4
      YrvQ7w1f5oqsF7FdaRb2CeRMVOQTLugJzQ2tMXvna5IWWAQNOOuyk47XSGx0DxJN
      hvhp4CZSvdFwHHTSfJcF+b8bQjIy1MOFhzTz/jZWZTxCmhX5fX6WwZwqq/8q4G9+
      pAoYHKrTyNov8xec7uwhzonkhFWUjDUtjRHTwU4dwDNkLGqPHVBljxsmsLsUskJs
      ByicpwsaShIak2hZaW94gqSmTOa9ho9VnMAzkZ9RQAWsgBTkrjy7gU02wYGIFEIy
      dMSdhPvf9DR4mas6gXP45Y2Oyq6ukzKaXoV03SgD+xRSqYj4y7q6dfdCkRiG7+2P
      Cfu7Mxg/02YF3TBnntCdv8dcp2j5sJ4RbN8bVznprDqqAufUHsUQNHPYEQvanglw
      TsgkLvh05FMDroJqGFloue0ajwe0L/pWCI59PJohAdng1fSd3ZcmP3zUBi9DifrG
      pG0ZRiLQjpxx40GOYYh8ycvO/5lFZz0/ufeoiETmlT/COSPXR3Z8feL9tpaeAxyY
      NA4BRKwNRnvPPB46dR5q7Z8ahOeNuFWcckolyFhSUHzV3FPTYiimM5ff4ZEvHW11
      pH4Fm6eMW5parc8jfg==
      -----END CERTIFICATE-----

# CRON

cron_monitor_monit_state: True

# MONIT

monit_mail_server:
  - {address: '127.0.0.1', port: '25'}

monit_mail_to:
  - {address: 'admin@example.com', filter: 'not on', events: ['instance', 'action']}

# MONIT_EXPORTER

monit_exporter_monitor_monit_state: True

# MOTD

motd_host_description: "Please add 'group_var' or 'host_var' file"

# NGINX

nginx_log_format_main: |-
  'remote_addr:$remote_addr - $remote_user [$time_local] request:"$request" '
  'status:$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" http_x_forwarded_for:"$http_x_forwarded_for"'

nginx_log_format_main_ssl: |-
  'remote_addr:$remote_addr - $remote_user [$time_local] request:"$request" '
  'status:$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" http_x_forwarded_for:"$http_x_forwarded_for" '
  '$ssl_protocol/$ssl_cipher '

nginx_monitor_monit_state: True

# NODE_EXPORTER

node_exporter_monitor_monit_state: True

# PF

pf_macros_all:
  # n_base
  - {name: 'n_base', value: '10.1.1.0/24', comment: 'n_base'}
  - {name: 'h_fw', value: '10.1.1.1', comment: 'firewall'}
  - {name: 'h_fp01', value: '10.1.1.11', comment: 'forward proxy'}

  # n_mgmt
  - {name: 'n_mgmt', value: '10.1.2.0/24', common: 'n_mgmt'}
  - {name: 'h_fw01', value: '10.1.2.2', comment: 'firewall 01'}
  - {name: 'h_fw02', value: '10.1.2.3', comment: 'firewall 02'}
  - {name: 'h_sw', value: '10.1.2.4', comment: 'switch'}
  - {name: 'h_vt', value: '10.1.2.9', comment: 'virtualization'}

  # n_dmz
  - {name: 'n_dmz', value: '10.1.3.0/24', common: 'n_dmz'}
  - {name: 'h_ns01', value: '10.1.3.11', comment: 'name server 01'}
  - {name: 'h_ns02', value: '10.1.3.13', comment: 'name server 01'}
  - {name: 'h_rp', value: '10.1.3.15', comment: 'reverse proxy'}
  - {name: 'h_ws', value: '10.1.3.17', comment: 'web server'}
  - {name: 'h_mx', value: '10.1.3.19', comment: 'mail server'}
  - {name: 'h_btc01', value: '10.1.3.21', comment: 'bitcoin server 01'}
  - {name: 'h_btc02', value: '10.1.3.23', comment: 'bitcoin server 02'}
  - {name: 'h_btc03', value: '10.1.3.25', comment: 'bitcoin server 03'}

  # n_tools
  - {name: 'n_tools', value: '10.1.4.0/24', common: 'n_tools'}
  - {name: 'h_vc', value: '10.1.4.11', comment: 'version control'}

  # n_clients
  - {name: 'n_clients', value: '10.1.5.0/24', common: 'n_clients'}
  - {name: 'h_nb', value: '10.1.5.11', comment: 'notebook'}

pf_filters_all:

  # ICMP

  # icmp from any to any
  - {action: 'pass', quick: True, direction: 'in', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'echoreq', comment: 'icmp echo request from any'}
  - {action: 'pass', quick: True, direction: 'out', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'echoreq', comment: 'icmp echo request to any'}
  - {action: 'pass', quick: True, direction: 'in', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'unreach', comment: 'icmp destination unreachable from any'}
  - {action: 'pass', quick: True, direction: 'out', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'unreach', comment: 'icmp destination unreachable to any'}
  - {action: 'pass', quick: True, direction: 'in', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'squench', comment: 'icmp source quench from any'}
  - {action: 'pass', quick: True, direction: 'out', version: 'inet', protocols: {'icmp'}, type: 'icmp-inet', code: 'squench', comment: 'icmp source quench to any'}

  # SSH

  # ssh from n_base, n_clients
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$n_base', '$n_clients'}, destinations: {'any'}, ports: {'22'}, comment: 'ssh from n_base, n_clients'}

  # MONITORING SERVER

  # node_exporter from h_ms
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$h_ms'}, destinations: {'any'}, ports: {'9100'}, comment: 'node_exporter from h_ms'}

  # haproxy_exporter from h_ms
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$h_ms'}, destinations: {'any'}, ports: {'9101'}, comment: 'haproxy_exporter from h_ms'}

  # mysqld_exporter  from h_ms
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$h_ms'}, destinations: {'any'}, ports: {'9104'}, comment: 'mysqld_exporter from h_ms'}

  # blackbox_exporter from h_ms
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$h_ms'}, destinations: {'any'}, ports: {'9115'}, comment: 'blackbox_exporter from h_ms'}

  # monit_exporter from h_ms
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$h_ms'}, destinations: {'any'}, ports: {'9388'}, comment: 'monit_exporter from h_ms'}

  # DNS

  # dns to h_fw, h_ns
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp', 'udp'}, sources: {'any'}, destinations: {'$h_fw', '$h_ns01', '$h_ns02'}, ports: {'53'}, comment: 'dns to h_fw, h_ns'}

  # NTP

  # ntp to h_fw
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'udp'}, sources: {'any'}, destinations: {'$h_fw'}, ports: {'123'}, comment: 'ntp to h_fw'}

  # MAIL EXCHANGER

  # smtp to h_mx
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp'}, sources: {'any'}, destinations: {'$h_mx'}, ports: {'25'}, comment: 'smtp to h_mx'}

  # BACKUP SERVER

  # https to h_bs
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp'}, sources: {'any'}, destinations: {'$h_bs'}, ports: {'443'} , comment: 'https to h_bs'}

  # LOG SERVER

  # syslog to h_ls
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp'}, sources: {'any'}, destinations: {'$h_ls'}, ports: {'514'} , comment: 'syslog to h_ls'}

  # FORWARD PROXY

  # squid to h_fp
  - {action: 'pass', direction: 'out', version: 'inet', protocols: {'tcp'}, sources: {'any'}, destinations: {'$h_fp'}, ports: {'3128'} , comment: 'squid to h_fp'}

# SYSLOGD

syslogd_monitor_monit_state: True

# SYSPATCH

syspatch_installurl:
 - {url: 'https://ftp.OpenBSD.org/pub/OpenBSD', comment: 'OpenBSD Packages'}

# OPENNTPD

openntpd_monitor_mail_from_address: 'root@example.com'

openntpd_monitor_mail_to_address: ['admin@example.com']

openntpd_monitor_mail_state: True

openntpd_monitor_monit_state: True

openntpd_server:
  - {address: 'ntp.example.com', comment: 'h_fw'}

# OPENSMTPD

opensmtpd_action_all:
  - {config: {'action "local" mbox alias <aliases>'}, comment: 'Action: local'}
  - {config: {'action "relay" relay host smtp://mail.example.com:25'}, comment: 'Action: relay'}

opensmtpd_monitor_monit_state: True

opensmtpd_root_mail_address: 'admin@example.com'

# OPENSSH

openssh_allow_users: ['example']

openssh_monitor_monit_state: True

openssh_password_authentication: False

# PACKAGE

package_config_all:
  - {name: 'colordiff', state: True}
  - {name: 'coreutils', state: True}
  - {name: 'curl', state: True}
  - {name: 'findutils', state: True}
  - {name: 'ggrep', state: True}
  - {name: 'gsed', state: True}
  - {name: 'gtar--', state: True}
  - {name: 'gnuwatch', state: True}
  - {name: 'htop', state: True}
  - {name: 'ifstat--', state: True}
  - {name: 'iftop', state: True}
  - {name: 'jq', state: True}
  - {name: 'lowdown', state: True}
  - {name: 'rsync--', state: True}
  - {name: 'unzip--', state: True}
  - {name: 'wget', state: True}
  - {name: 'zip', state: True}

# RESOLVER

resolver_domain: 'example.com'

resolver_nameserver:
  - {address: '10.1.1.1', comment: 'h_fw'}

resolver_search: ['example.com']

# RESTIC

restic_cacert: '/etc/ssl/ca.example.com.crt'

restic_keep_daily: 30

restic_keep_hourly: 168

restic_keep_monthly: 240

restic_keep_weekly: 12

restic_monitor_mail_from_address: 'root@example.com'

restic_monitor_mail_to_address: ['admin@example.com']

restic_monitor_mail_state: True

restic_monitor_prom_state: True

restic_password: 'NMhTJr,sftD-vA5uG!v.WE2+a9D87DeE'

restic_server_address: 'backup.example.com'

restic_server_password: '5EWf-AjpSQ_due9x4M-tRb_g5Qq5g_LN'

restic_server_username: 'restic'

# ROOT

root_password: '$2b$10$Jua/9rgOstNEVRKz11ncGO1EG.Z1krMLkOurJe4jNHVEU0UZV4fI6'

# RSYSLOG

rsyslog_monitor_monit_state: True

# SHELL

shell_ftp_proxy: 'http://proxy.example.com:3128'

shell_http_proxy: 'http://proxy.example.com:3128'

shell_https_proxy: 'http://proxy.example.com:3128'

shell_no_proxy: ['localhost', '127.0.0.1', '::1', 'bs.example.com', 'backup.example.com']

# SUDO

sudo_config_all:
  - name: 'root'
    state: True
    order: '10'
    comment: 'root'
    config: |
      # root
      root ALL=(ALL) ALL

  - name: 'example'
    state: True
    order: '50'
    config: |
      # example
      example ALL=(root) NOPASSWD: ALL

# USER

user_config_all:
  - name: 'example'
    state: True
    comment: 'example'
    uid: '1000'
    group: 'example'
    groups: ['wheel']
    groups_append: True
    password: '$2b$10$6cmx3Y2CaKFoAwqWmKXxtOCD0FWgPZ.QWor2m9W8U.m5E7ygTCb..'
    password_update: True
    shell: '/bin/bash'
    authorized_keys:
      - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII4JgSg6a8MHOvpODaZhvkOnEdWHQSdbkFaGHRYHW3qH example@example.com'
