---

# MOTD

motd_host_description: 'Web Server'

# PF

pf_filters_host:
  - {action: 'pass', direction: 'in', version: 'inet', protocols: {'tcp'}, sources: {'$h_rp', '$n_clients'}, destinations: {'any'}, ports: {'80', '443'}, comment: 'http, https from h_rp, n_clients'}
