---

#-------------------------------------------------------------------------------
# ALERTMANAGER
#-------------------------------------------------------------------------------

alertmanager_config:
  - section: 'global'
    config: |
      smtp_from: 'ms@example.com'
      smtp_hello: 'ms.example.com'
      smtp_smarthost: 'mail.example.com:25'
      smtp_auth_username: ''
      smtp_auth_password: ''
      smtp_require_tls: false

  - section: 'route'
    config: |
      receiver: 'user'
      group_by: ['instance', 'alert']
      group_wait: 1m
      group_interval: 30m
      repeat_interval: 150m
      routes:
      - match:
          severity: 'critical'
        receiver: 'user'

  - section: 'inhibit_rules'
    config: |
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname']

  - section: 'receivers'
    config: |
      - name: 'user'
        email_configs:
        - to: 'user@example.com'

#-------------------------------------------------------------------------------
# GRAFANA
#-------------------------------------------------------------------------------

grafana_smtp_from_address: 'ms@example.com'

grafana_smtp_from_name: 'ms'

grafana_smtp_host: 'mail.example.com'

grafana_smtp_port: '25'

grafana_smtp_state: 'true'

#-------------------------------------------------------------------------------
# MOTD
#-------------------------------------------------------------------------------

motd_host_description: 'Monitoring Server'

#-------------------------------------------------------------------------------
# NGINX
#-------------------------------------------------------------------------------

nginx_config:
  - name: 'alert.example.com'
    state: 'true'
    port: 80
    hsts_state: 'true'
    xss_protection_state: 'true'
    config: |
      return 301 https://$server_name$request_uri;

  - name: 'alert.example.com'
    state: 'true'
    port: 443
    hsts_state: 'true'
    xss_protection_state: 'true'
    ssl_state: 'true'
    ssl_ecdh_curve: 'secp384r1'
    ssl_certificate: '/etc/pki/example/wildcard.example.com.crt'
    ssl_certificate_key: '/etc/pki/example/wildcard.example.com.pem'
    config: |
      location / {
        proxy_pass                         http://localhost:9093/;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

  - name: 'monitor.example.com'
    state: 'true'
    port: 80
    hsts_state: 'true'
    xss_protection_state: 'true'
    config: |
      return 301 https://$server_name$request_uri;

  - name: 'monitor.example.com'
    state: 'true'
    port: 443
    hsts_state: 'true'
    xss_protection_state: 'true'
    ssl_state: 'true'
    ssl_ecdh_curve: 'secp384r1'
    ssl_certificate: '/etc/pki/example/wildcard.example.com.crt'
    ssl_certificate_key: '/etc/pki/example/wildcard.example.com.pem'
    config: |
      location / {
        proxy_pass                         http://localhost:3000/;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

  - name: 'metric.example.com'
    state: 'true'
    port: 80
    hsts_state: 'true'
    xss_protection_state: 'true'
    config: |
      return 301 https://$server_name$request_uri;

  - name: 'metric.example.com'
    state: 'true'
    port: 443
    hsts_state: 'true'
    xss_protection_state: 'true'
    ssl_state: 'true'
    ssl_ecdh_curve: 'secp384r1'
    ssl_certificate: '/etc/pki/example/wildcard.example.com.crt'
    ssl_certificate_key: '/etc/pki/example/wildcard.example.com.pem'
    config: |
      location / {
        proxy_pass                         http://localhost:9090/;
        proxy_http_version                 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "Upgrade";
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

#-------------------------------------------------------------------------------
# NFTABLES
#-------------------------------------------------------------------------------

nftables_filter_host:
  - {action: 'accept', direction: 'in', version: 'ipv4', protocol: 'tcp', sources: {'10.1.3.0/24', '10.1.5.0/24'}, ports: {'80', '443'}, comment: 'http, https from n_dmz, n_clients'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', ports: {'80', '443'}, comment: 'http, https to any (blackbox_exporter)'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'9100'}, comment: 'node_exporter to internal-networks'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'9101'}, comment: 'haproxy_exporter to internal-networks'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'9104'}, comment: 'mysqld_exporter to internal-networks'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'9115'}, comment: 'blackbox_exporter to internal-networks'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'9388'}, comment: 'monit_exporter to internal-networks'}

#-------------------------------------------------------------------------------
# PROMETHEUS
#-------------------------------------------------------------------------------

prometheus_blackbox_exporter_http_ip4_basic_manual_hosts:
  - {address: 'https://web.example.com', hostname: 'web'}
  - {address: 'https://wiki.example.com', hostname: 'wiki'}

prometheus_blackbox_exporter_icmp_ip4_manual_hosts:
  - {address: '10.1.1.11', hostname: 'fp01'}
  - {address: '10.1.2.2', hostname: 'fw01'}
  - {address: '10.1.2.3', hostname: 'fw02'}
  - {address: '10.1.3.11', hostname: 'ns01'}
  - {address: '10.1.3.15', hostname: 'ws01'}

prometheus_node_exporter_target_manual_hosts:
  - {address: '10.1.1.11', hostname: 'fp01'}
  - {address: '10.1.2.2', hostname: 'fw01'}
  - {address: '10.1.2.3', hostname: 'fw02'}
  - {address: '10.1.3.11', hostname: 'ns01'}
  - {address: '10.1.3.15', hostname: 'ws01'}

prometheus_smokeping_prober_state: 'true'

prometheus_alerting_rules: |
  groups:
      - name: common
        rules:

        #-----------------------------------------------------------------------
        # FILESYSTEM
        #-----------------------------------------------------------------------

        - alert: "Filesystem 'boot' threshold exceeded"
          expr: ( (sum by (instance) (node_filesystem_size_bytes{mountpoint="/boot"}) - sum by (instance) (node_filesystem_avail_bytes{mountpoint="/boot"})) / sum by (instance) (node_filesystem_size_bytes{mountpoint="/boot"}) ) * 100 > 80
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} - Filesystem '/boot' threshold exceeded"
            description: "Filesystem '/boot' usage: {% raw %}{{ $value }}{% endraw %}%"

        - alert: "Filesystem 'root' threshold exceeded"
          expr: ( (sum by (instance) (node_filesystem_size_bytes{mountpoint="/"}) - sum by (instance) (node_filesystem_avail_bytes{mountpoint="/"})) / sum by (instance) (node_filesystem_size_bytes{mountpoint="/"}) ) * 100 > 80
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} - Filesystem '/' threshold exceeded"
            description: "Filesystem '/' usage: {% raw %}{{ $value }}{% endraw %}%"

        - alert: "Filesystem 'swap' threshold exceeded"
          expr: ( (sum by (instance) (node_memory_SwapTotal_bytes)) - (sum by (instance) (node_memory_SwapFree_bytes)) ) / (sum by (instance) (node_memory_SwapTotal_bytes)) * 100 > 70
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %}  Filesystem 'swap' threshold exceeded"
            description: "Filesystem 'swap' usage: {% raw %}{{ $value }}{% endraw %}%"

        - alert: "Filesystem 'data' threshold exceeded"
          expr: ( (sum by (instance) (node_filesystem_size_bytes{mountpoint="/data"}) - sum by (instance) (node_filesystem_avail_bytes{mountpoint="/data"})) / sum by (instance) (node_filesystem_size_bytes{mountpoint="/data"}) ) * 100 > 90
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} - Filesystem '/data' threshold exceeded"
            description: "Filesystem '/data' usage: {% raw %}{{ $value }}{% endraw %}%"

        #-----------------------------------------------------------------------
        # CPU USER
        #-----------------------------------------------------------------------

        - alert: "CPU 'user' threshold 10mAVG exceeded"
          expr: avg by (instance)(irate(node_cpu_seconds_total{instance!="virt_005_s",instance!="backend_dev_s",instance!="backend_test_s",job="node",mode="user"}[10m])) * 100 > 80
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} - CPU 'user' threshold exceeded"
            description: "CPU 'user' load has been above 80% for at least 5 minutes. Current CPU 'user' average value: {% raw %}{{ $value }}{% endraw %}%."

        - alert: "CPU 'user' threshold 60mAVG exceeded"
          expr: avg by (instance)(irate(node_cpu_seconds_total{instance!="virt_005_s",instance!="backend_dev_s",instance!="backend_test_s",job="node",mode="user"}[10m])) * 100 > 60
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} - CPU 'user' threshold 60mAVG exceeded"
            description: "CPU 'user' load has been above 60% for at least 60 minutes. Current CPU 'user' average value: {% raw %}{{ $value }}{% endraw %}%."

        #-----------------------------------------------------------------------
        # CPU SYSTEM
        #-----------------------------------------------------------------------

        - alert: "CPU 'system' threshold 10mAVG exceeded"
          expr: avg by (instance)(irate(node_cpu_seconds_total{job="node",mode="system"}[10m])) * 100 > 80
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} - CPU 'system' threshold 10mAVG exceeded"
            description: "CPU 'system' load has been above 80% for at least 5 minutes. Current CPU 'system' average value: {% raw %}{{ $value }}{% endraw %}%."

        - alert: "CPU 'system' threshold 60mAVG exceeded"
          expr: avg by (instance)(irate(node_cpu_seconds_total{job="node",mode="system"}[60m])) * 100 > 60
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} - CPU 'system' threshold 60mAVG exceeded"
            description: "CPU 'system' load has been above 60% for at least 60 minutes. Current CPU 'system' average value: {% raw %}{{ $value }}{% endraw %}%."

        #-----------------------------------------------------------------------
        # CPU IOWAIT
        #-----------------------------------------------------------------------

        - alert: "CPU 'IOwait' threshold 10mAVG exceeded"
          expr: avg by (instance)(irate(node_cpu_seconds_total{job="node",mode="iowait"}[10m])) * 100 > 80
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} - CPU 'IOwait' threshold 5mAVG exceeded"
            description: "CPU 'IOwait' load has been above 80% for at least 5 minutes. Current CPU 'IOwait' average value: {% raw %}{{ $value }}{% endraw %}%."

        - alert: "CPU 'IOwait' threshold 60mAVG exceeded"
          expr: avg by (instance)(irate(node_cpu_seconds_total{job="node",mode="iowait"}[60m])) * 100 > 60
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} - CPU 'IOwait' threshold 60mAVG exceeded"
            description: "CPU 'IOwait' load has been above 60% for at least 60 minutes. Current CPU 'IOwait' average value: {% raw %}{{ $value }}{% endraw %}%."

        #-----------------------------------------------------------------------
        # MEMORY
        #-----------------------------------------------------------------------

        - alert: "Memory usage exceeded"
          expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
          for: 30s
          labels:
            severity: warning
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} - Memory threshold exceeded."
            description: "Memory usage has been over {% raw %}{{ $value }}{% endraw %}%"

        #-----------------------------------------------------------------------
        # PING
        #-----------------------------------------------------------------------

        - alert: "Ping check failed"
          expr: probe_success{job="icmp_ip4"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "{% raw %} {{ $labels.instance }} {% endraw %} has been down for two minutes"
            description: "Ping check failed. {% raw %} {{ $labels.instance }} {% endraw %} has been down for two minutes."

#-------------------------------------------------------------------------------
# RESTIC
#-------------------------------------------------------------------------------

restic_state: 'remove'

#-------------------------------------------------------------------------------
# RSYSLOG
#-------------------------------------------------------------------------------

rsyslog_config_host:
  - name: nginx
    comment: Nginx
    section: input
    config:
      - {type: imfile, File: '/var/log/nginx/*_access.log', Tag: nginx, Severity: info, Facility: local6}
      - {type: imfile, File: '/var/log/nginx/*_error.log', Tag: nginx, Severity: info, Facility: local6}

#-------------------------------------------------------------------------------
# SMOKEPING_PROBER
#-------------------------------------------------------------------------------

smokeping_prober_hosts:
  - 'localhost'

#-------------------------------------------------------------------------------
# SELINUX
#-------------------------------------------------------------------------------

selinux_mode: 'permissive'
