---

#-------------------------------------------------------------------------------
# HTTPD
#-------------------------------------------------------------------------------

httpd_global_config: |
  # Configures the OCSP stapling cache
  SSLStaplingCache "shmcb:logs/stapling-cache(150000)"

httpd_config:
  - name: 'example.com'
    alias: ['web.example.com', 'www.example.com']
    state: 'true'
    port: '80'
    server_admin: 'admin@example.com'
    document_root: '/var/www/html'
    xss_protection_state: 'true'
    config: |
      Redirect permanent /  https://example.com/

  - name: 'example.com'
    alias: ['web.example.com', 'www.example.com']
    state: 'true'
    port: '443'
    server_admin: 'admin@example.com'
    document_root: '/var/www/html'
    xss_protection_state: 'true'
    ssl_state: 'true'
    ssl_certificate: '/etc/letsencrypt/live/example.com/cert.pem'
    ssl_certificate_key: '/etc/letsencrypt/live/example.com/privkey.pem'
    ssl_certificate_chain: '/etc/letsencrypt/live/example.com/chain.pem'
    config: |
      SSLUseStapling  On
      SSLOCSPProxyURL "http://fp.example.com:3128/"

      SSLProxyEngine On

      <Location "/">
        ProxyPass        "https://example.com/"
        ProxyPassReverse "https://example.com/"
      </Location>

#-------------------------------------------------------------------------------
# MOD_SECURITY
#-------------------------------------------------------------------------------

mod_security_sec_rule_engine: 'enable'

#-------------------------------------------------------------------------------
# MOD_SECURITY_CRS3
#-------------------------------------------------------------------------------

mod_security_crs3_sec_default_action:
  - "phase:1,log,auditlog,redirect:'http://%{request_headers.host}/',tag:'Host: %{request_headers.host}'"
  - "phase:2,log,auditlog,redirect:'http://%{request_headers.host}/',tag:'Host: %{request_headers.host}'"

#-------------------------------------------------------------------------------
# MONIT
#-------------------------------------------------------------------------------

monit_config_host:
  - name: 'httpd'
    state: 'true'
    comment: 'httpd'
    config: |
      check process httpd with pidfile "/run/httpd/httpd.pid"
        start program = "/sbin/service httpd start"
        stop program = "/sbin/service httpd stop"
        if failed host 127.0.0.1 port 80 type tcp with timeout 10 seconds then alert
        if failed host 127.0.0.1 port 443 type tcp with timeout 10 seconds then alert
        if 5 restarts within 5 cycles then unmonitor

#-------------------------------------------------------------------------------
# MOTD
#-------------------------------------------------------------------------------

motd_host_description: 'Reverse Proxy'

#-------------------------------------------------------------------------------
# NFTABLES
#-------------------------------------------------------------------------------

nftables_filter_host:
  - {action: 'accept', direction: 'in', version: 'ipv4', protocol: 'tcp', ports: {'80', '443'}, comment: 'http, https from any'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', destinations: {'10.0.0.0/8'}, ports: {'80', '443'}, comment: 'http, https to internal-networks'}
  - {action: 'accept', direction: 'out', version: 'ipv4', protocol: 'tcp', ports: {'443'}, comment: 'https to any (letsencrypt)'}
