---

# ALL

# Pre
- hosts: all
  become: True
  roles:
    - role: package
    - role: syslogd
    - role: syspatch
    - role: rc
    - role: periodic
    - role: root
    - role: shell
    - role: bash
    - role: user
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

# Main
- hosts: all
  become: True
  roles:
    - role: hosts
    - role: hostname
    - role: hostname_if
    - role: motd
    - role: node_exporter
    - role: openntpd
    - role: opensmtpd
    - role: openssh
    - role: resolver
    - role: restic
    - role: sudo
    - role: tmux
    - role: vim
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

# Post
- hosts: all
  become: True
  roles:
    - role: monit
    - role: monit_exporter
    - role: pf
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'
