---

# FORWARD PROXY

- hosts: fp
  become: True
  roles:
    - role: squid
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'
