---

# NAME SERVER

- hosts: ns
  become: True
  roles:
    - role: nsd
  environment:
    http_proxy: 'http://proxy.example.com:3128'
    https_proxy: 'http://proxy.example.com:3128'
    ftp_proxy: 'http://proxy.example.com:3128'
