---

# NETWORK

network_config:
  - {name: 'lo', type: 'loopback'}
  - {name: 'eno1', type: 'manual'}
  - {name: 'eno2', type: 'manual'}
  - {name: 'eno3', type: 'manual'}
  - {name: 'eno4', type: 'manual'}

  - name: 'bond0'
    type: 'manual'
    mtu: 1500
    ovs_type: 'OVSBond'
    ovs_bridge: 'vmbr0'
    ovs_bonds: ['eno1', 'eno2', 'eno3', 'eno4']
    ovs_options: ['bond_mode=balance-tcp', 'lacp=active', 'other_config:lacp-time=fast']

  - name: 'vmbr0'
    type: 'manual'
    mtu: 1500
    ovs_type: 'OVSBridge'
    ovs_ports: ['bond0', 'base', 'mgmt', 'dmz', 'tools']

  - name: 'base'
    type: 'static'
    mtu: 1500
    ovs_type: 'OVSIntPort'
    ovs_bridge: 'vmbr0'
    ovs_options: ['tag=11']

  - name: 'mgmt'
    type: 'static'
    mtu: 1500
    ovs_type: 'OVSIntPort'
    ovs_bridge: 'vmbr0'
    ovs_options: ['tag=12']
    address: '10.1.12.10'
    netmask: '255.255.255.0'
    gateway: '10.1.12.1'

  - name: 'dmz'
    type: 'static'
    mtu: 1500
    ovs_type: 'OVSIntPort'
    ovs_bridge: 'vmbr0'
    ovs_options: ['tag=13']

  - name: 'tools'
    type: 'static'
    mtu: 1500
    ovs_type: 'OVSIntPort'
    ovs_bridge: 'vmbr0'
    ovs_options: ['tag=14']
