---

# ALL

# Pre
- hosts: all
  become: yes
  roles:
    - role: hosts
    - role: apt
    - role: package
    - role: shell
    - role: bash
    - role: user
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

# Main
- hosts: all
  become: yes
  roles:
    - role: auditd
    - role: chrony
    - role: fstrim
    - role: hostname
    - role: issue
    - role: locale
    - role: motd
    - role: node_exporter
    - role: opensmtpd
    - role: openssh
    - role: resolver
    - role: restic
    - role: root
    - role: rsyslog
    - role: sudo
    - role: sysctl
    - role: systemd
    - role: timezone
    - role: tmux
    - role: vim
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'

# Post
- hosts: all
  become: yes
  roles:
    - role: monit
    - role: monit_exporter
    - role: nftables
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'
