---

# BTC

- hosts: btc
  become: True
  roles:
    - role: bitcoin_core
  environment:
    http_proxy: 'http://fp.example.com:3128'
    https_proxy: 'http://fp.example.com:3128'
    ftp_proxy: 'http://fp.example.com:3128'
