---

# INTRUSION DETECTION SYSTEM

- hosts: ids
  become: True
  roles:
    - role: suricata
  environment:
    http_proxy: 'http://proxy.example.com:3128'
    https_proxy: 'http://proxy.example.com:3128'
    ftp_proxy: 'http://proxy.example.com:3128'
