---

#-------------------------------------------------------------------------------
# ZFS
#-------------------------------------------------------------------------------

zfs_scrub_pools_pools: ['data01', 'data02']
